<?php

namespace app\modules\hlib\components;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * Class Application
 * @package app\components
 */
class Application extends \yii\web\Application
{
    /**
     * @param array $config
     * @throws \yii\base\InvalidConfigException
     */
    public function preInit(&$config)
    {
        parent::preInit($config); // TODO: Change the autogenerated stub
        //
        mb_internal_encoding('UTF-8');
        list($code, $lang) = $config['params']['locale'];
        setlocale(LC_TIME, $code, $lang);
        //réglage de la timezone sinon date() renvoie l'heure UTC
        date_default_timezone_set($config['params']['timezone']);
    }

    /**
     * @param $containerKey
     * @return mixed
     */
    public function getClassName($containerKey)
    {
        $item = ArrayHelper::getValue(Yii::$container->getDefinitions(), $containerKey);
        return $item ? $item['class'] : $containerKey;

    }

}